default: &default
  num_data_workers: 5
  # model
  reps: 2
  depth: 9
  filters: 32
  input_kernel: 7
  coord_conv: !!bool True
  pool_mode: 'sum'
  spatial_size: 292
  num_input: 4
  feature_size: 1
  allow_bias: !!bool False
  # optimization
  lr: 0.001
  optimizer: 'Adam'
  max_epochs: 10
  max_cosine_lr_epochs: 10
  batch_size: 200
  valid_batch_size: 100
  # misc
  log_to_screen: !!bool True
  save_checkpoint: !!bool True
  # data locations
  train_path: '/pscratch/sd/e/ehinkle/nd_ana/sheep_single_shower/ELECTRON_SAMPLES/CONVERT2H5/TRAIN/'
  test_path: '/pscratch/sd/e/ehinkle/nd_ana/sheep_single_shower/ELECTRON_SAMPLES/CONVERT2H5/TEST/'
  val_path: '/pscratch/sd/e/ehinkle/nd_ana/sheep_single_shower/ELECTRON_SAMPLES/CONVERT2H5/VALIDATION/'
  # detector-based data augmentation
  start_xyz_range: [[-60, -60, -60], 
                    [ 60,  60,  60]] 
  detector_active_regions: [[[  3.069, -62.076,   2.4620001],
                             [ 63.931,  62.076,  64.538]],
                            [[  3.069, -62.076, -64.538],
                             [ 63.931,  62.076,  -2.4620001]],
                            [[-63.931, -62.076,   2.462],
                             [ -3.069,  62.076,  64.537994]],
                            [[-63.931, -62.076, -64.538],
                             [ -3.069,  62.076, -2.4620001]]]
  random_seed: 0
  voxel_size: [0.4434, 0.4434, 0.4434]
  min_visible_energy: 10
  fid_vol_cut: 2.0

test:  # inherit configs from the alias default
  <<: *default
  batch_size: 50